server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/hb_cinema_db"
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ptatamde@gmail.com # Email gửi
    password: fpjp rksv ckch jgbt # Mật khẩu hoặc App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmnCode: "58X4B4HP"
    secretKey: "VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ"
    returnUrl: "http://localhost:3000/identity/payment/vn-pay-callback"
    version: "2.1.0"
    command: "pay"
    orderType: "other"
#để key ở đây để bảo mật, để người khác không lấy được chữ ký
#  Khóa này sẽ được sử dụng để mã hóa và giải mã các JWT (JSON Web Tokens).
jwt:
  signerKey: "5z6FgquJbieYiLWnIX+VwsT3LQnEw5G9VFXJ7kqVfhaYbeam0SYWmPl/8EBK84v1"
  valid-duration: 7200 # in second
  refreshable-duration: 720000 # in seconds
